// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADfNh1IM_sowYRSad9P9Rl6VMjs35VOFM',
    appId: '1:956895943857:web:c130051728b85aa2ab9690',
    messagingSenderId: '956895943857',
    projectId: 'nantestudio-7d35c',
    authDomain: 'nantestudio-7d35c.firebaseapp.com',
    storageBucket: 'nantestudio-7d35c.firebasestorage.app',
    measurementId: 'G-5GREDC3DP4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXW7ZB7xIAy9CGPYxLYeFdnHLCE1yRZAw',
    appId: '1:956895943857:android:92494a7689529269ab9690',
    messagingSenderId: '956895943857',
    projectId: 'nantestudio-7d35c',
    storageBucket: 'nantestudio-7d35c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_vEZ0w58dcvdkSyqODNuy5RVRvmKx3i8',
    appId: '1:956895943857:ios:ce6088420cecd0eeab9690',
    messagingSenderId: '956895943857',
    projectId: 'nantestudio-7d35c',
    storageBucket: 'nantestudio-7d35c.firebasestorage.app',
    iosBundleId: 'com.nantestudio.antworld',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_vEZ0w58dcvdkSyqODNuy5RVRvmKx3i8',
    appId: '1:956895943857:ios:ce6088420cecd0eeab9690',
    messagingSenderId: '956895943857',
    projectId: 'nantestudio-7d35c',
    storageBucket: 'nantestudio-7d35c.firebasestorage.app',
    iosBundleId: 'com.nantestudio.antworld',
  );
}
